version: '3.8'

services:
  app:
    container_name: notes_api
    build: ./
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./app:/src/app
    ports:
      - ${APP_HOST_PORT}:8000
    restart: always
    env_file:
      - .env

  db:
    container_name: notes_db
    image: postgres:16.4
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    ports:
      - ${POSTGRES_DB_HOST_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always