
services:
  app:
    container_name: notes_api
    build: ./
    depends_on:
      - db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./app:/src/app
    networks:
      - default
    ports:
      - ${APP_HOST_PORT}:8000
    restart: always
#    command: alembic upgrade head
    env_file:
      - .env

  db:
    container_name: notes_db
    image: postgres:16.4
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - default
    ports:
      - ${DB_PORT}:5432
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always