"""Initial table creation

Revision ID: 89ce4cd2bde1
Revises: 
Create Date: 2024-08-27 22:04:24.908199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '89ce4cd2bde1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('user_name', sa.String(length=30), nullable=False),
                    sa.Column('user_hashed_password', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('user_id'),
                    sa.UniqueConstraint('user_name')
                    )
    op.create_table('notes',
                    sa.Column('note_id', sa.Integer(), nullable=False),
                    sa.Column('note_title', sa.String(length=50), nullable=False),
                    sa.Column('note_content', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"),
                              nullable=False),
                    sa.Column('by_user', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['by_user'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('note_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    op.drop_table('users')
    # ### end Alembic commands ###
